services:
  go_db:
    container_name: go_db
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myrestapi_db
    volumes:
      - myrestapi_pg_data:/var/lib/postgresql/data

volumes:
  myrestapi_pg_data: {}
